from __future__ import annotations

import logging
import time
import uuid
from collections.abc import AsyncIterator, Awaitable, Callable
from contextlib import asynccontextmanager

from fastapi import FastAPI, Request, Response
from fastapi.middleware.cors import CORSMiddleware
from sqlalchemy import text

from app.api import analysis, auth, keys, public, scores, votes
from app.config import settings
from app.db.base import Base
from app.db.session import engine

API_DESCRIPTION = """
**AI Fake Or Real** tells you whether content at a URL was generated by AI,
combining automated analysis with crowd votes.

## For app developers
The simplest integration is a single call:

```
GET /api/v1/check?url=<the content url>
```

It returns a `verdict` (`human`, `mixed`, `ai_generated`, or `unknown`) plus the
underlying signals. Works for Reddit, Instagram, Facebook, YouTube, TikTok, X,
and most pages with link-preview metadata.

**API keys** are free — create one at `POST /api/v1/keys` and send it as the
`X-API-Key` header so your usage is attributed (usage-based pricing may apply to
high-volume use in the future). See the developer guide in `docs/API.md`.
"""

TAGS_METADATA = [
    {"name": "public", "description": "The simple, stable public API for other apps."},
    {"name": "api-keys", "description": "Create and inspect API keys (free)."},
    {"name": "scores", "description": "Raw score lookups."},
    {"name": "votes", "description": "Crowd voting."},
    {"name": "analysis", "description": "Trigger and read AI analysis."},
    {"name": "auth", "description": "User accounts for weighted voting."},
]

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(name)s %(message)s",
)
logger = logging.getLogger("aifakeorreal.access")


@asynccontextmanager
async def lifespan(app: FastAPI) -> AsyncIterator[None]:
    Base.metadata.create_all(bind=engine)
    yield


app = FastAPI(
    title="AI Fake Or Real API",
    description=API_DESCRIPTION,
    version="0.1.0",
    openapi_tags=TAGS_METADATA,
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.CORS_ORIGINS,
    allow_origin_regex=settings.CORS_ORIGIN_REGEX,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.middleware("http")
async def request_context(
    request: Request, call_next: Callable[[Request], Awaitable[Response]]
) -> Response:
    """Attach a request ID and log method, path, status, and latency."""
    request_id = request.headers.get("X-Request-ID") or uuid.uuid4().hex
    start = time.perf_counter()
    response = await call_next(request)
    elapsed_ms = (time.perf_counter() - start) * 1000
    response.headers["X-Request-ID"] = request_id
    logger.info(
        "%s %s %s %.1fms id=%s",
        request.method,
        request.url.path,
        response.status_code,
        elapsed_ms,
        request_id,
    )
    return response


app.include_router(public.router, prefix="/api/v1")
app.include_router(keys.router, prefix="/api/v1")
app.include_router(auth.router, prefix="/api/v1")
app.include_router(scores.router, prefix="/api/v1")
app.include_router(votes.router, prefix="/api/v1")
app.include_router(analysis.router, prefix="/api/v1")


@app.get("/")
def root() -> dict:
    return {"status": "ok", "name": "AI Fake Or Real API", "version": "0.1.0"}


@app.get("/health")
def health() -> Response:
    """Liveness/readiness probe: verifies database connectivity."""
    from fastapi.responses import JSONResponse

    db_ok = True
    try:
        with engine.connect() as conn:
            conn.execute(text("SELECT 1"))
    except Exception:
        db_ok = False

    status_code = 200 if db_ok else 503
    return JSONResponse(
        status_code=status_code,
        content={"status": "ok" if db_ok else "degraded", "database": db_ok},
    )
