// LLM-based AI content detection with multi-provider failover.
//
// Waterfall chain (8 providers, cheapest free tiers):
//   Text:  Gemini Flash → Groq → OpenAI → Anthropic → Mistral → Cohere → Together → Cloudflare
//   Image: Gemini Flash → OpenAI → Anthropic → Together (vision-capable only)
//   Video: Gemini Flash (only provider with native video input)
//
// Each provider returns null on failure; the next in chain is tried automatically.

// --- API keys (all optional — set whichever you have) ---
const GEMINI_API_KEY = process.env.GEMINI_API_KEY || "";
const GROQ_API_KEY = process.env.GROQ_API_KEY || "";
const OPENAI_API_KEY = process.env.OPENAI_API_KEY || "";
const ANTHROPIC_API_KEY = process.env.ANTHROPIC_API_KEY || "";
const MISTRAL_API_KEY = process.env.MISTRAL_API_KEY || "";
const COHERE_API_KEY = process.env.COHERE_API_KEY || "";
const TOGETHER_API_KEY = process.env.TOGETHER_API_KEY || "";
const CLOUDFLARE_ACCOUNT_ID = process.env.CLOUDFLARE_ACCOUNT_ID || "";
const CLOUDFLARE_API_TOKEN = process.env.CLOUDFLARE_API_TOKEN || "";

const MAX_TEXT_LENGTH = 3000;
const REQUEST_TIMEOUT_MS = 15_000;

// --- Types ---

export type ContentType = "text" | "image" | "video" | "mixed";

export interface LLMDetectionResult {
  score: number;          // 0 (human) to 1 (AI)
  confidence: "low" | "medium" | "high";
  reasoning: string;
  provider: string;
  contentType: ContentType;
}

export interface DetectionInput {
  text?: string;
  imageUrls?: string[];   // URLs to images on the page
  videoUrl?: string;      // URL to a video (for Gemini native video)
}

// --- Prompts ---

const TEXT_SYSTEM_PROMPT = `You are an AI content detector. Analyze the following text and determine whether it was written by a human or generated by AI (ChatGPT, Claude, Gemini, Llama, etc.).

Respond with ONLY a JSON object (no markdown, no code fences):
{"score": <0.0-1.0>, "confidence": "<low|medium|high>", "reasoning": "<one sentence>"}

- score: 0.0 = definitely human-written, 1.0 = definitely AI-generated, 0.5 = uncertain
- Consider: vocabulary patterns, sentence uniformity, hedging language, lack of personal voice, formulaic structure, excessive em-dashes, tricolons
- Short texts (< 50 words) should get low confidence
- News articles and Wikipedia may look AI-like but are usually human — don't over-flag`;

const IMAGE_SYSTEM_PROMPT = `You are an AI image detector. Analyze the following image and determine whether it was created by a human (photograph, hand-drawn, painted) or generated by AI (Midjourney, DALL-E, Stable Diffusion, Firefly, etc.).

Respond with ONLY a JSON object (no markdown, no code fences):
{"score": <0.0-1.0>, "confidence": "<low|medium|high>", "reasoning": "<one sentence>"}

- score: 0.0 = definitely human-created, 1.0 = definitely AI-generated, 0.5 = uncertain
- Look for: impossible anatomy (extra fingers, merged limbs), uncanny smoothness, texture inconsistencies, watermark artifacts, plastic-looking skin, incoherent text in image, weird backgrounds, unnatural lighting, symmetric perfection
- Photographs with normal imperfections (noise, blur, lens flare) are likely human
- Digital art and illustrations require more careful analysis`;

const VIDEO_SYSTEM_PROMPT = `You are an AI video/media detector. Analyze the following media and determine whether it was created by a human or generated by AI (Sora, Runway, Pika, Kling, etc.).

Respond with ONLY a JSON object (no markdown, no code fences):
{"score": <0.0-1.0>, "confidence": "<low|medium|high>", "reasoning": "<one sentence>"}

- score: 0.0 = definitely human-created, 1.0 = definitely AI-generated, 0.5 = uncertain
- Look for: temporal inconsistencies, morphing artifacts, unnatural motion, physics violations, flickering details, text that changes between frames`;

// --- Helpers ---

function truncate(text: string): string {
  if (text.length <= MAX_TEXT_LENGTH) return text;
  return text.slice(0, MAX_TEXT_LENGTH) + "\n[...truncated]";
}

function parseResponse(raw: string): Omit<LLMDetectionResult, "provider" | "contentType"> | null {
  try {
    const cleaned = raw.replace(/^```json?\s*/i, "").replace(/\s*```$/i, "").trim();
    const parsed = JSON.parse(cleaned);
    const score = Number(parsed.score);
    if (isNaN(score) || score < 0 || score > 1) return null;
    return {
      score: Math.round(score * 100) / 100,
      confidence: ["low", "medium", "high"].includes(parsed.confidence)
        ? parsed.confidence
        : "low",
      reasoning: String(parsed.reasoning || "").slice(0, 200),
    };
  } catch {
    return null;
  }
}

/** Fetch with a timeout. */
async function fetchWithTimeout(
  url: string,
  init: RequestInit,
  timeoutMs = REQUEST_TIMEOUT_MS
): Promise<Response> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  try {
    return await fetch(url, { ...init, signal: controller.signal });
  } finally {
    clearTimeout(timer);
  }
}

/** OpenAI-compatible chat completion (works for OpenAI, Groq, Together, Mistral). */
async function openaiCompatible(
  baseUrl: string,
  apiKey: string,
  model: string,
  systemPrompt: string,
  userContent: Array<{ type: string; text?: string; image_url?: { url: string } }>,
  providerName: string,
): Promise<LLMDetectionResult | null> {
  try {
    const resp = await fetchWithTimeout(`${baseUrl}/chat/completions`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        model,
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: userContent },
        ],
        max_tokens: 150,
        temperature: 0.1,
      }),
    });
    if (!resp.ok) {
      console.error(`${providerName} error: ${resp.status}`);
      return null;
    }
    const data = await resp.json();
    const raw = data.choices?.[0]?.message?.content || "";
    const parsed = parseResponse(raw);
    return parsed ? { ...parsed, provider: providerName, contentType: "text" } : null;
  } catch (e: any) {
    console.error(`${providerName} failed:`, e.message);
    return null;
  }
}

// =====================================================================
//  Provider implementations
// =====================================================================

// --- 1. Google Gemini (best free tier, vision + video) ---
async function gemini(input: DetectionInput, ct: ContentType): Promise<LLMDetectionResult | null> {
  if (!GEMINI_API_KEY) return null;
  const prompt = ct === "image" ? IMAGE_SYSTEM_PROMPT : ct === "video" ? VIDEO_SYSTEM_PROMPT : TEXT_SYSTEM_PROMPT;

  const parts: Array<{ text?: string; inlineData?: { mimeType: string; data: string }; fileData?: { mimeUri: string; mimeType: string } }> = [];

  // Add text if present
  if (input.text) parts.push({ text: truncate(input.text) });

  // Add images
  if (input.imageUrls?.length) {
    for (const url of input.imageUrls.slice(0, 3)) {
      try {
        const imgResp = await fetchWithTimeout(url, {}, 10_000);
        if (imgResp.ok) {
          const buf = await imgResp.arrayBuffer();
          const b64 = Buffer.from(buf).toString("base64");
          const mime = imgResp.headers.get("content-type") || "image/jpeg";
          parts.push({ inlineData: { mimeType: mime, data: b64 } });
        }
      } catch { /* skip image */ }
    }
  }

  // Add video URL (Gemini can process video URLs directly via fileData)
  if (input.videoUrl) {
    parts.push({ text: `Video URL for analysis: ${input.videoUrl}` });
  }

  if (parts.length === 0) return null;

  try {
    const resp = await fetchWithTimeout(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${GEMINI_API_KEY}`,
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          systemInstruction: { parts: [{ text: prompt }] },
          contents: [{ parts }],
          generationConfig: { maxOutputTokens: 150, temperature: 0.1 },
        }),
      }
    );
    if (!resp.ok) { console.error(`Gemini error: ${resp.status}`); return null; }
    const data = await resp.json();
    const raw = data.candidates?.[0]?.content?.parts?.[0]?.text || "";
    const parsed = parseResponse(raw);
    return parsed ? { ...parsed, provider: "gemini", contentType: ct } : null;
  } catch (e: any) {
    console.error("Gemini failed:", e.message);
    return null;
  }
}

// --- 2. Groq (fastest inference, text only, generous free tier) ---
async function groq(input: DetectionInput): Promise<LLMDetectionResult | null> {
  if (!GROQ_API_KEY || !input.text) return null;
  return openaiCompatible(
    "https://api.groq.com/openai/v1", GROQ_API_KEY,
    "llama-3.3-70b-versatile", TEXT_SYSTEM_PROMPT,
    [{ type: "text", text: truncate(input.text) }], "groq"
  );
}

// --- 3. OpenAI (vision capable) ---
async function openai(input: DetectionInput, ct: ContentType): Promise<LLMDetectionResult | null> {
  if (!OPENAI_API_KEY) return null;
  const prompt = ct === "image" ? IMAGE_SYSTEM_PROMPT : TEXT_SYSTEM_PROMPT;
  const content: Array<{ type: string; text?: string; image_url?: { url: string } }> = [];

  if (input.text) content.push({ type: "text", text: truncate(input.text) });
  if (ct === "image" && input.imageUrls?.length) {
    for (const url of input.imageUrls.slice(0, 3)) {
      content.push({ type: "image_url", image_url: { url } });
    }
  }
  if (content.length === 0) return null;

  const result = await openaiCompatible(
    "https://api.openai.com/v1", OPENAI_API_KEY,
    "gpt-4o-mini", prompt, content, "openai"
  );
  if (result) result.contentType = ct;
  return result;
}

// --- 4. Anthropic (vision capable) ---
async function anthropic(input: DetectionInput, ct: ContentType): Promise<LLMDetectionResult | null> {
  if (!ANTHROPIC_API_KEY) return null;
  const prompt = ct === "image" ? IMAGE_SYSTEM_PROMPT : TEXT_SYSTEM_PROMPT;

  const content: Array<{ type: string; text?: string; source?: { type: string; media_type: string; data: string } }> = [];

  if (input.text) content.push({ type: "text", text: truncate(input.text) });

  // Anthropic requires base64 for images
  if (ct === "image" && input.imageUrls?.length) {
    for (const url of input.imageUrls.slice(0, 3)) {
      try {
        const imgResp = await fetchWithTimeout(url, {}, 10_000);
        if (imgResp.ok) {
          const buf = await imgResp.arrayBuffer();
          const b64 = Buffer.from(buf).toString("base64");
          const mime = imgResp.headers.get("content-type") || "image/jpeg";
          content.push({
            type: "image",
            source: { type: "base64", media_type: mime, data: b64 },
          });
        }
      } catch { /* skip */ }
    }
  }

  if (content.length === 0) return null;

  try {
    const resp = await fetchWithTimeout("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-api-key": ANTHROPIC_API_KEY,
        "anthropic-version": "2023-06-01",
      },
      body: JSON.stringify({
        model: "claude-haiku-4-5-20251001",
        max_tokens: 150,
        system: prompt,
        messages: [{ role: "user", content }],
      }),
    });
    if (!resp.ok) { console.error(`Anthropic error: ${resp.status}`); return null; }
    const data = await resp.json();
    const raw = data.content?.[0]?.text || "";
    const parsed = parseResponse(raw);
    return parsed ? { ...parsed, provider: "anthropic", contentType: ct } : null;
  } catch (e: any) {
    console.error("Anthropic failed:", e.message);
    return null;
  }
}

// --- 5. Mistral (text only, 1 RPM free) ---
async function mistral(input: DetectionInput): Promise<LLMDetectionResult | null> {
  if (!MISTRAL_API_KEY || !input.text) return null;
  return openaiCompatible(
    "https://api.mistral.ai/v1", MISTRAL_API_KEY,
    "mistral-small-latest", TEXT_SYSTEM_PROMPT,
    [{ type: "text", text: truncate(input.text) }], "mistral"
  );
}

// --- 6. Cohere (text only, 20 RPM free) ---
async function cohere(input: DetectionInput): Promise<LLMDetectionResult | null> {
  if (!COHERE_API_KEY || !input.text) return null;
  try {
    const resp = await fetchWithTimeout("https://api.cohere.com/v2/chat", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${COHERE_API_KEY}`,
      },
      body: JSON.stringify({
        model: "command-r",
        messages: [
          { role: "system", content: TEXT_SYSTEM_PROMPT },
          { role: "user", content: truncate(input.text) },
        ],
        max_tokens: 150,
        temperature: 0.1,
      }),
    });
    if (!resp.ok) { console.error(`Cohere error: ${resp.status}`); return null; }
    const data = await resp.json();
    const raw = data.message?.content?.[0]?.text || "";
    const parsed = parseResponse(raw);
    return parsed ? { ...parsed, provider: "cohere", contentType: "text" } : null;
  } catch (e: any) {
    console.error("Cohere failed:", e.message);
    return null;
  }
}

// --- 7. Together AI (vision via Llama, $5 free credit) ---
async function together(input: DetectionInput, ct: ContentType): Promise<LLMDetectionResult | null> {
  if (!TOGETHER_API_KEY) return null;
  const isVision = ct === "image" && input.imageUrls?.length;

  const model = isVision
    ? "meta-llama/Llama-3.2-11B-Vision-Instruct-Turbo"
    : "meta-llama/Llama-3.3-70B-Instruct-Turbo";

  const prompt = isVision ? IMAGE_SYSTEM_PROMPT : TEXT_SYSTEM_PROMPT;
  const content: Array<{ type: string; text?: string; image_url?: { url: string } }> = [];

  if (input.text) content.push({ type: "text", text: truncate(input.text) });
  if (isVision) {
    for (const url of input.imageUrls!.slice(0, 2)) {
      content.push({ type: "image_url", image_url: { url } });
    }
  }
  if (content.length === 0) return null;

  const result = await openaiCompatible(
    "https://api.together.xyz/v1", TOGETHER_API_KEY,
    model, prompt, content, "together"
  );
  if (result) result.contentType = ct;
  return result;
}

// --- 8. Cloudflare Workers AI (text only, 10K req/day free) ---
async function cloudflare(input: DetectionInput): Promise<LLMDetectionResult | null> {
  if (!CLOUDFLARE_ACCOUNT_ID || !CLOUDFLARE_API_TOKEN || !input.text) return null;
  try {
    const resp = await fetchWithTimeout(
      `https://api.cloudflare.com/client/v4/accounts/${CLOUDFLARE_ACCOUNT_ID}/ai/run/@cf/meta/llama-3.1-8b-instruct`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${CLOUDFLARE_API_TOKEN}`,
        },
        body: JSON.stringify({
          messages: [
            { role: "system", content: TEXT_SYSTEM_PROMPT },
            { role: "user", content: truncate(input.text) },
          ],
          max_tokens: 150,
          temperature: 0.1,
        }),
      }
    );
    if (!resp.ok) { console.error(`Cloudflare error: ${resp.status}`); return null; }
    const data = await resp.json();
    const raw = data.result?.response || "";
    const parsed = parseResponse(raw);
    return parsed ? { ...parsed, provider: "cloudflare", contentType: "text" } : null;
  } catch (e: any) {
    console.error("Cloudflare failed:", e.message);
    return null;
  }
}

// =====================================================================
//  Failover chains
// =====================================================================

type ProviderFn = (input: DetectionInput, ct: ContentType) => Promise<LLMDetectionResult | null>;

interface ProviderEntry {
  name: string;
  fn: ProviderFn;
  hasKey: () => boolean;
  supports: ContentType[];
}

const ALL_PROVIDERS: ProviderEntry[] = [
  { name: "gemini",     fn: (i, ct) => gemini(i, ct),       hasKey: () => !!GEMINI_API_KEY,    supports: ["text", "image", "video", "mixed"] },
  { name: "groq",       fn: (i) => groq(i),                 hasKey: () => !!GROQ_API_KEY,      supports: ["text"] },
  { name: "openai",     fn: (i, ct) => openai(i, ct),       hasKey: () => !!OPENAI_API_KEY,    supports: ["text", "image", "mixed"] },
  { name: "anthropic",  fn: (i, ct) => anthropic(i, ct),    hasKey: () => !!ANTHROPIC_API_KEY,  supports: ["text", "image", "mixed"] },
  { name: "mistral",    fn: (i) => mistral(i),              hasKey: () => !!MISTRAL_API_KEY,   supports: ["text"] },
  { name: "cohere",     fn: (i) => cohere(i),               hasKey: () => !!COHERE_API_KEY,    supports: ["text"] },
  { name: "together",   fn: (i, ct) => together(i, ct),     hasKey: () => !!TOGETHER_API_KEY,  supports: ["text", "image"] },
  { name: "cloudflare", fn: (i) => cloudflare(i),           hasKey: () => !!(CLOUDFLARE_ACCOUNT_ID && CLOUDFLARE_API_TOKEN), supports: ["text"] },
];

/** Determine what type of content we're analyzing. */
function classifyContent(input: DetectionInput): ContentType {
  const hasText = !!input.text && input.text.trim().length >= 20;
  const hasImage = !!input.imageUrls?.length;
  const hasVideo = !!input.videoUrl;

  if (hasVideo) return "video";
  if (hasImage && hasText) return "mixed";
  if (hasImage) return "image";
  return "text";
}

/**
 * Detect AI content using the LLM waterfall chain.
 * Tries each provider in order until one succeeds.
 * For images/video, only providers with vision support are tried.
 * Returns null if all providers fail (caller falls back to heuristics).
 */
export async function detectWithLLM(input: DetectionInput): Promise<LLMDetectionResult | null> {
  const ct = classifyContent(input);

  // For text-only, require minimum length
  if (ct === "text" && (!input.text || input.text.trim().length < 50)) return null;

  const available = ALL_PROVIDERS.filter(
    (p) => p.hasKey() && p.supports.includes(ct)
  );

  if (available.length === 0) return null;

  for (const provider of available) {
    const result = await provider.fn(input, ct);
    if (result) {
      console.log(`LLM detection by ${provider.name}: score=${result.score} (${ct})`);
      return result;
    }
    console.log(`LLM provider ${provider.name} failed for ${ct}, trying next...`);
  }

  console.log(`All LLM providers failed for ${ct}`);
  return null;
}

/** Check if any LLM provider is configured. */
export function hasLLMProvider(): boolean {
  return ALL_PROVIDERS.some((p) => p.hasKey());
}

/** List configured providers (for diagnostics). */
export function listProviders(): Array<{ name: string; configured: boolean; supports: ContentType[] }> {
  return ALL_PROVIDERS.map((p) => ({
    name: p.name,
    configured: p.hasKey(),
    supports: p.supports,
  }));
}
