// LLM-based AI content detection with multi-provider failover.
//
// Waterfall chain (8 providers, cheapest free tiers):
//   Text:  Gemini Flash → Groq → OpenAI → Anthropic → Mistral → Cohere → Together → Cloudflare
//   Image: Gemini Flash → OpenAI → Anthropic → Together (vision-capable only)
//   Video: Gemini Flash (only provider with native video input)
//
// Each provider returns null on failure; the next in chain is tried automatically.
//
// Keys: the server's own keys (from env) are the default. Callers may pass
// per-request keys (BYOK — "bring your own keys") which override the env keys,
// plus a preferred provider order. BYOK keys are used transiently for that one
// request and are never persisted or logged.

// --- API keys (all optional — set whichever you have) ---
const GEMINI_API_KEY = process.env.GEMINI_API_KEY || "";
const GROQ_API_KEY = process.env.GROQ_API_KEY || "";
const OPENAI_API_KEY = process.env.OPENAI_API_KEY || "";
const ANTHROPIC_API_KEY = process.env.ANTHROPIC_API_KEY || "";
const MISTRAL_API_KEY = process.env.MISTRAL_API_KEY || "";
const COHERE_API_KEY = process.env.COHERE_API_KEY || "";
const TOGETHER_API_KEY = process.env.TOGETHER_API_KEY || "";
const CLOUDFLARE_ACCOUNT_ID = process.env.CLOUDFLARE_ACCOUNT_ID || "";
const CLOUDFLARE_API_TOKEN = process.env.CLOUDFLARE_API_TOKEN || "";

const MAX_TEXT_LENGTH = 3000;
const REQUEST_TIMEOUT_MS = 15_000;

// --- Types ---

export type ContentType = "text" | "image" | "video" | "mixed";

/** Per-provider credentials. All fields optional; empty means "not configured". */
export interface ProviderKeys {
  gemini: string;
  groq: string;
  openai: string;
  anthropic: string;
  mistral: string;
  cohere: string;
  together: string;
  cloudflareAccountId: string;
  cloudflareApiToken: string;
}

/** The server's own keys, read once from the environment. */
const ENV_KEYS: ProviderKeys = {
  gemini: GEMINI_API_KEY,
  groq: GROQ_API_KEY,
  openai: OPENAI_API_KEY,
  anthropic: ANTHROPIC_API_KEY,
  mistral: MISTRAL_API_KEY,
  cohere: COHERE_API_KEY,
  together: TOGETHER_API_KEY,
  cloudflareAccountId: CLOUDFLARE_ACCOUNT_ID,
  cloudflareApiToken: CLOUDFLARE_API_TOKEN,
};

/**
 * Merge user-supplied keys over the server defaults. Empty/whitespace values
 * are ignored so a partial BYOK config still falls back to the server's keys
 * for the providers the user didn't supply.
 */
function mergeKeys(user?: Partial<ProviderKeys>): ProviderKeys {
  if (!user) return ENV_KEYS;
  const merged: ProviderKeys = { ...ENV_KEYS };
  for (const field of Object.keys(merged) as (keyof ProviderKeys)[]) {
    const value = user[field];
    if (typeof value === "string" && value.trim()) merged[field] = value.trim();
  }
  return merged;
}

/** Options for a detection call. */
export interface DetectionOptions {
  keys?: Partial<ProviderKeys>; // BYOK — overrides server keys per request
  preferred?: string[]; // provider names to try first, in order
}

export interface LLMDetectionResult {
  score: number;          // 0 (human) to 1 (AI)
  confidence: "low" | "medium" | "high";
  reasoning: string;
  provider: string;
  contentType: ContentType;
}

export interface DetectionInput {
  text?: string;
  imageUrls?: string[];   // URLs to images on the page
  videoUrl?: string;      // URL to a video (for Gemini native video)
}

// --- Prompts ---

const TEXT_SYSTEM_PROMPT = `You are an AI content detector. Analyze the following text and determine whether it was written by a human or generated by AI (ChatGPT, Claude, Gemini, Llama, etc.).

Respond with ONLY a JSON object (no markdown, no code fences):
{"score": <0.0-1.0>, "confidence": "<low|medium|high>", "reasoning": "<one sentence>"}

- score: 0.0 = definitely human-written, 1.0 = definitely AI-generated, 0.5 = uncertain
- Consider: vocabulary patterns, sentence uniformity, hedging language, lack of personal voice, formulaic structure, excessive em-dashes, tricolons
- Short texts (< 50 words) should get low confidence
- News articles and Wikipedia may look AI-like but are usually human — don't over-flag`;

const IMAGE_SYSTEM_PROMPT = `You are an AI image detector. Analyze the following image and determine whether it was created by a human (photograph, hand-drawn, painted) or generated by AI (Midjourney, DALL-E, Stable Diffusion, Firefly, etc.).

Respond with ONLY a JSON object (no markdown, no code fences):
{"score": <0.0-1.0>, "confidence": "<low|medium|high>", "reasoning": "<one sentence>"}

- score: 0.0 = definitely human-created, 1.0 = definitely AI-generated, 0.5 = uncertain
- Look for: impossible anatomy (extra fingers, merged limbs), uncanny smoothness, texture inconsistencies, watermark artifacts, plastic-looking skin, incoherent text in image, weird backgrounds, unnatural lighting, symmetric perfection
- Photographs with normal imperfections (noise, blur, lens flare) are likely human
- Digital art and illustrations require more careful analysis`;

const VIDEO_SYSTEM_PROMPT = `You are an AI video/media detector. Analyze the following media and determine whether it was created by a human or generated by AI (Sora, Runway, Pika, Kling, etc.).

Respond with ONLY a JSON object (no markdown, no code fences):
{"score": <0.0-1.0>, "confidence": "<low|medium|high>", "reasoning": "<one sentence>"}

- score: 0.0 = definitely human-created, 1.0 = definitely AI-generated, 0.5 = uncertain
- Look for: temporal inconsistencies, morphing artifacts, unnatural motion, physics violations, flickering details, text that changes between frames`;

// --- Helpers ---

function truncate(text: string): string {
  if (text.length <= MAX_TEXT_LENGTH) return text;
  return text.slice(0, MAX_TEXT_LENGTH) + "\n[...truncated]";
}

/**
 * Guard against SSRF: we only fetch image bytes from public http(s) URLs.
 * Blocks loopback, private/link-local ranges, cloud metadata endpoints, and
 * non-http schemes so a page can't point the server at internal services.
 * (Does not defend against DNS rebinding; acceptable for best-effort image pulls.)
 */
function isSafeRemoteUrl(raw: string): boolean {
  let u: URL;
  try {
    u = new URL(raw);
  } catch {
    return false;
  }
  if (u.protocol !== "http:" && u.protocol !== "https:") return false;
  const host = u.hostname.toLowerCase().replace(/^\[|\]$/g, "");
  if (host === "localhost" || host === "0.0.0.0" || host.endsWith(".local")) return false;
  if (host === "metadata.google.internal") return false;
  // IPv4 private / loopback / link-local
  if (/^127\./.test(host)) return false;
  if (/^10\./.test(host)) return false;
  if (/^192\.168\./.test(host)) return false;
  if (/^172\.(1[6-9]|2\d|3[01])\./.test(host)) return false;
  if (/^169\.254\./.test(host)) return false; // includes 169.254.169.254 metadata
  // IPv6 loopback / link-local / unique-local
  if (host === "::1" || host.startsWith("fe80:") || host.startsWith("fc") || host.startsWith("fd")) return false;
  return true;
}

function parseResponse(raw: string): Omit<LLMDetectionResult, "provider" | "contentType"> | null {
  try {
    const cleaned = raw.replace(/^```json?\s*/i, "").replace(/\s*```$/i, "").trim();
    const parsed = JSON.parse(cleaned);
    const score = Number(parsed.score);
    if (isNaN(score) || score < 0 || score > 1) return null;
    return {
      score: Math.round(score * 100) / 100,
      confidence: ["low", "medium", "high"].includes(parsed.confidence)
        ? parsed.confidence
        : "low",
      reasoning: String(parsed.reasoning || "").slice(0, 200),
    };
  } catch {
    return null;
  }
}

/** Fetch with a timeout. */
async function fetchWithTimeout(
  url: string,
  init: RequestInit,
  timeoutMs = REQUEST_TIMEOUT_MS
): Promise<Response> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  try {
    return await fetch(url, { ...init, signal: controller.signal });
  } finally {
    clearTimeout(timer);
  }
}

/** OpenAI-compatible chat completion (works for OpenAI, Groq, Together, Mistral). */
async function openaiCompatible(
  baseUrl: string,
  apiKey: string,
  model: string,
  systemPrompt: string,
  userContent: Array<{ type: string; text?: string; image_url?: { url: string } }>,
  providerName: string,
): Promise<LLMDetectionResult | null> {
  try {
    const resp = await fetchWithTimeout(`${baseUrl}/chat/completions`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        model,
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: userContent },
        ],
        max_tokens: 150,
        temperature: 0.1,
      }),
    });
    if (!resp.ok) {
      console.error(`${providerName} error: ${resp.status}`);
      return null;
    }
    const data = await resp.json();
    const raw = data.choices?.[0]?.message?.content || "";
    const parsed = parseResponse(raw);
    return parsed ? { ...parsed, provider: providerName, contentType: "text" } : null;
  } catch (e: any) {
    console.error(`${providerName} failed:`, e.message);
    return null;
  }
}

// =====================================================================
//  Provider implementations
// =====================================================================

// --- 1. Google Gemini (best free tier, vision + video) ---
async function gemini(input: DetectionInput, ct: ContentType, keys: ProviderKeys): Promise<LLMDetectionResult | null> {
  if (!keys.gemini) return null;
  const prompt = ct === "image" ? IMAGE_SYSTEM_PROMPT : ct === "video" ? VIDEO_SYSTEM_PROMPT : TEXT_SYSTEM_PROMPT;

  const parts: Array<{ text?: string; inlineData?: { mimeType: string; data: string }; fileData?: { mimeUri: string; mimeType: string } }> = [];

  // Add text if present
  if (input.text) parts.push({ text: truncate(input.text) });

  // Add images
  if (input.imageUrls?.length) {
    for (const url of input.imageUrls.slice(0, 3)) {
      if (!isSafeRemoteUrl(url)) continue;
      try {
        const imgResp = await fetchWithTimeout(url, {}, 10_000);
        if (imgResp.ok) {
          const buf = await imgResp.arrayBuffer();
          const b64 = Buffer.from(buf).toString("base64");
          const mime = imgResp.headers.get("content-type") || "image/jpeg";
          parts.push({ inlineData: { mimeType: mime, data: b64 } });
        }
      } catch { /* skip image */ }
    }
  }

  // Add video URL (Gemini can process video URLs directly via fileData)
  if (input.videoUrl) {
    parts.push({ text: `Video URL for analysis: ${input.videoUrl}` });
  }

  if (parts.length === 0) return null;

  try {
    const resp = await fetchWithTimeout(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${keys.gemini}`,
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          systemInstruction: { parts: [{ text: prompt }] },
          contents: [{ parts }],
          generationConfig: { maxOutputTokens: 150, temperature: 0.1 },
        }),
      }
    );
    if (!resp.ok) { console.error(`Gemini error: ${resp.status}`); return null; }
    const data = await resp.json();
    const raw = data.candidates?.[0]?.content?.parts?.[0]?.text || "";
    const parsed = parseResponse(raw);
    return parsed ? { ...parsed, provider: "gemini", contentType: ct } : null;
  } catch (e: any) {
    console.error("Gemini failed:", e.message);
    return null;
  }
}

// --- 2. Groq (fastest inference, text only, generous free tier) ---
async function groq(input: DetectionInput, keys: ProviderKeys): Promise<LLMDetectionResult | null> {
  if (!keys.groq || !input.text) return null;
  return openaiCompatible(
    "https://api.groq.com/openai/v1", keys.groq,
    "llama-3.3-70b-versatile", TEXT_SYSTEM_PROMPT,
    [{ type: "text", text: truncate(input.text) }], "groq"
  );
}

// --- 3. OpenAI (vision capable) ---
async function openai(input: DetectionInput, ct: ContentType, keys: ProviderKeys): Promise<LLMDetectionResult | null> {
  if (!keys.openai) return null;
  const prompt = ct === "image" ? IMAGE_SYSTEM_PROMPT : TEXT_SYSTEM_PROMPT;
  const content: Array<{ type: string; text?: string; image_url?: { url: string } }> = [];

  if (input.text) content.push({ type: "text", text: truncate(input.text) });
  if (ct === "image" && input.imageUrls?.length) {
    for (const url of input.imageUrls.slice(0, 3)) {
      content.push({ type: "image_url", image_url: { url } });
    }
  }
  if (content.length === 0) return null;

  const result = await openaiCompatible(
    "https://api.openai.com/v1", keys.openai,
    "gpt-4o-mini", prompt, content, "openai"
  );
  if (result) result.contentType = ct;
  return result;
}

// --- 4. Anthropic (vision capable) ---
async function anthropic(input: DetectionInput, ct: ContentType, keys: ProviderKeys): Promise<LLMDetectionResult | null> {
  if (!keys.anthropic) return null;
  const prompt = ct === "image" ? IMAGE_SYSTEM_PROMPT : TEXT_SYSTEM_PROMPT;

  const content: Array<{ type: string; text?: string; source?: { type: string; media_type: string; data: string } }> = [];

  if (input.text) content.push({ type: "text", text: truncate(input.text) });

  // Anthropic requires base64 for images
  if (ct === "image" && input.imageUrls?.length) {
    for (const url of input.imageUrls.slice(0, 3)) {
      if (!isSafeRemoteUrl(url)) continue;
      try {
        const imgResp = await fetchWithTimeout(url, {}, 10_000);
        if (imgResp.ok) {
          const buf = await imgResp.arrayBuffer();
          const b64 = Buffer.from(buf).toString("base64");
          const mime = imgResp.headers.get("content-type") || "image/jpeg";
          content.push({
            type: "image",
            source: { type: "base64", media_type: mime, data: b64 },
          });
        }
      } catch { /* skip */ }
    }
  }

  if (content.length === 0) return null;

  try {
    const resp = await fetchWithTimeout("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-api-key": keys.anthropic,
        "anthropic-version": "2023-06-01",
      },
      body: JSON.stringify({
        model: "claude-haiku-4-5-20251001",
        max_tokens: 150,
        system: prompt,
        messages: [{ role: "user", content }],
      }),
    });
    if (!resp.ok) { console.error(`Anthropic error: ${resp.status}`); return null; }
    const data = await resp.json();
    const raw = data.content?.[0]?.text || "";
    const parsed = parseResponse(raw);
    return parsed ? { ...parsed, provider: "anthropic", contentType: ct } : null;
  } catch (e: any) {
    console.error("Anthropic failed:", e.message);
    return null;
  }
}

// --- 5. Mistral (text only, 1 RPM free) ---
async function mistral(input: DetectionInput, keys: ProviderKeys): Promise<LLMDetectionResult | null> {
  if (!keys.mistral || !input.text) return null;
  return openaiCompatible(
    "https://api.mistral.ai/v1", keys.mistral,
    "mistral-small-latest", TEXT_SYSTEM_PROMPT,
    [{ type: "text", text: truncate(input.text) }], "mistral"
  );
}

// --- 6. Cohere (text only, 20 RPM free) ---
async function cohere(input: DetectionInput, keys: ProviderKeys): Promise<LLMDetectionResult | null> {
  if (!keys.cohere || !input.text) return null;
  try {
    const resp = await fetchWithTimeout("https://api.cohere.com/v2/chat", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${keys.cohere}`,
      },
      body: JSON.stringify({
        model: "command-r",
        messages: [
          { role: "system", content: TEXT_SYSTEM_PROMPT },
          { role: "user", content: truncate(input.text) },
        ],
        max_tokens: 150,
        temperature: 0.1,
      }),
    });
    if (!resp.ok) { console.error(`Cohere error: ${resp.status}`); return null; }
    const data = await resp.json();
    const raw = data.message?.content?.[0]?.text || "";
    const parsed = parseResponse(raw);
    return parsed ? { ...parsed, provider: "cohere", contentType: "text" } : null;
  } catch (e: any) {
    console.error("Cohere failed:", e.message);
    return null;
  }
}

// --- 7. Together AI (vision via Llama, $5 free credit) ---
async function together(input: DetectionInput, ct: ContentType, keys: ProviderKeys): Promise<LLMDetectionResult | null> {
  if (!keys.together) return null;
  const isVision = ct === "image" && input.imageUrls?.length;

  const model = isVision
    ? "meta-llama/Llama-3.2-11B-Vision-Instruct-Turbo"
    : "meta-llama/Llama-3.3-70B-Instruct-Turbo";

  const prompt = isVision ? IMAGE_SYSTEM_PROMPT : TEXT_SYSTEM_PROMPT;
  const content: Array<{ type: string; text?: string; image_url?: { url: string } }> = [];

  if (input.text) content.push({ type: "text", text: truncate(input.text) });
  if (isVision) {
    for (const url of input.imageUrls!.slice(0, 2)) {
      content.push({ type: "image_url", image_url: { url } });
    }
  }
  if (content.length === 0) return null;

  const result = await openaiCompatible(
    "https://api.together.xyz/v1", keys.together,
    model, prompt, content, "together"
  );
  if (result) result.contentType = ct;
  return result;
}

// --- 8. Cloudflare Workers AI (text only, 10K req/day free) ---
async function cloudflare(input: DetectionInput, keys: ProviderKeys): Promise<LLMDetectionResult | null> {
  if (!keys.cloudflareAccountId || !keys.cloudflareApiToken || !input.text) return null;
  try {
    const resp = await fetchWithTimeout(
      `https://api.cloudflare.com/client/v4/accounts/${keys.cloudflareAccountId}/ai/run/@cf/meta/llama-3.1-8b-instruct`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${keys.cloudflareApiToken}`,
        },
        body: JSON.stringify({
          messages: [
            { role: "system", content: TEXT_SYSTEM_PROMPT },
            { role: "user", content: truncate(input.text) },
          ],
          max_tokens: 150,
          temperature: 0.1,
        }),
      }
    );
    if (!resp.ok) { console.error(`Cloudflare error: ${resp.status}`); return null; }
    const data = await resp.json();
    const raw = data.result?.response || "";
    const parsed = parseResponse(raw);
    return parsed ? { ...parsed, provider: "cloudflare", contentType: "text" } : null;
  } catch (e: any) {
    console.error("Cloudflare failed:", e.message);
    return null;
  }
}

// =====================================================================
//  Failover chains
// =====================================================================

type ProviderFn = (input: DetectionInput, ct: ContentType, keys: ProviderKeys) => Promise<LLMDetectionResult | null>;

interface ProviderEntry {
  name: string;
  fn: ProviderFn;
  hasKey: (keys: ProviderKeys) => boolean;
  supports: ContentType[];
}

const ALL_PROVIDERS: ProviderEntry[] = [
  { name: "gemini",     fn: (i, ct, k) => gemini(i, ct, k),    hasKey: (k) => !!k.gemini,    supports: ["text", "image", "video", "mixed"] },
  { name: "groq",       fn: (i, _ct, k) => groq(i, k),         hasKey: (k) => !!k.groq,      supports: ["text"] },
  { name: "openai",     fn: (i, ct, k) => openai(i, ct, k),    hasKey: (k) => !!k.openai,    supports: ["text", "image", "mixed"] },
  { name: "anthropic",  fn: (i, ct, k) => anthropic(i, ct, k), hasKey: (k) => !!k.anthropic, supports: ["text", "image", "mixed"] },
  { name: "mistral",    fn: (i, _ct, k) => mistral(i, k),      hasKey: (k) => !!k.mistral,   supports: ["text"] },
  { name: "cohere",     fn: (i, _ct, k) => cohere(i, k),       hasKey: (k) => !!k.cohere,    supports: ["text"] },
  { name: "together",   fn: (i, ct, k) => together(i, ct, k),  hasKey: (k) => !!k.together,  supports: ["text", "image"] },
  { name: "cloudflare", fn: (i, _ct, k) => cloudflare(i, k),   hasKey: (k) => !!(k.cloudflareAccountId && k.cloudflareApiToken), supports: ["text"] },
];

/** Determine what type of content we're analyzing. */
function classifyContent(input: DetectionInput): ContentType {
  const hasText = !!input.text && input.text.trim().length >= 20;
  const hasImage = !!input.imageUrls?.length;
  const hasVideo = !!input.videoUrl;

  if (hasVideo) return "video";
  if (hasImage && hasText) return "mixed";
  if (hasImage) return "image";
  return "text";
}

/** Order available providers by the caller's preference, stable for the rest. */
function applyPreference(providers: ProviderEntry[], preferred?: string[]): ProviderEntry[] {
  if (!preferred?.length) return providers;
  const rank = (name: string): number => {
    const i = preferred.indexOf(name);
    return i === -1 ? Number.MAX_SAFE_INTEGER : i;
  };
  return providers
    .map((p, i) => ({ p, i }))
    .sort((a, b) => rank(a.p.name) - rank(b.p.name) || a.i - b.i)
    .map(({ p }) => p);
}

/**
 * Detect AI content using the LLM waterfall chain.
 * Tries each provider in order until one succeeds.
 * For images/video, only providers with vision support are tried.
 * Returns null if all providers fail (caller falls back to heuristics).
 *
 * @param opts.keys     BYOK keys that override the server's env keys per request.
 * @param opts.preferred Provider names to try first, in order.
 */
export async function detectWithLLM(
  input: DetectionInput,
  opts?: DetectionOptions,
): Promise<LLMDetectionResult | null> {
  const keys = mergeKeys(opts?.keys);
  const ct = classifyContent(input);

  // For text-only, require minimum length
  if (ct === "text" && (!input.text || input.text.trim().length < 50)) return null;

  const available = applyPreference(
    ALL_PROVIDERS.filter((p) => p.hasKey(keys) && p.supports.includes(ct)),
    opts?.preferred,
  );

  if (available.length === 0) return null;

  for (const provider of available) {
    const result = await provider.fn(input, ct, keys);
    if (result) {
      console.log(`LLM detection by ${provider.name}: score=${result.score} (${ct})`);
      return result;
    }
    console.log(`LLM provider ${provider.name} failed for ${ct}, trying next...`);
  }

  console.log(`All LLM providers failed for ${ct}`);
  return null;
}

/** Check if any LLM provider is configured (optionally including BYOK keys). */
export function hasLLMProvider(keys?: Partial<ProviderKeys>): boolean {
  const merged = mergeKeys(keys);
  return ALL_PROVIDERS.some((p) => p.hasKey(merged));
}

/** List configured providers (for diagnostics). */
export function listProviders(keys?: Partial<ProviderKeys>): Array<{ name: string; configured: boolean; supports: ContentType[] }> {
  const merged = mergeKeys(keys);
  return ALL_PROVIDERS.map((p) => ({
    name: p.name,
    configured: p.hasKey(merged),
    supports: p.supports,
  }));
}
